# Header

menu:
  主页: '/'
  搞机: '/tags/搞机/'
  笔记: '/tags/建站笔记/'
  留言: '/MessageBoard/'
  关于: '/aboutme/'

# SubNav
subnav:
  github: 'https://github.com/MonoLogueChi'
  #weibo: "https://weibo.com/u/5226533927/"
  #zhihu: "#"
  #qq: "#"
  weixin: 'https://oss.xxwhite.com/static/wechat.png'
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: 'https://space.bilibili.com/28474682/'
  #acfun: "#"
  mail: 'mailto:xxwhite@foxmail.com'
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  rss: '/atom.xml'

rss: '/atom.xml'

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: ''
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false
fancybox: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '请作者吃辣条'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 'https://oss.xxwhite.com/static/alipay.png'
# 微信二维码图片地址
weixin: 'https://oss.xxwhite.com/static/wechatpay.png'

# 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有copyright不为false的文章均有版权声明
copyright_type: 2

# 备案信息，没有请留空
beian: '蒙ICP备17004911号-1'

# 又拍云开发者计划图片链接，没有请留空
upyun: 'https://oss.xxwhite.com/static/upyun.png'

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
#baidu_analytics: '893dcb25b87bcda2f682b3a6d5c537f7'
#google_analytics: 'UA-113200574-1'
favicon: 'https://oss.xxwhite.com/static/favicon.png'

#你的头像url
avatar: 'https://oss.xxwhite.com/static/avatar.jpg'

#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
#changyan_appid: 
#changyan_conf: 

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret
  
  
#6、Valine https://valine.js.org
valine: 
 appid: 'BOnDPDiz9EeoGAC11JdnV9mw-gzGzoHsz' #Leancloud应用的appId
 appkey: 'gNFFgOahNl9DGsyX1WearaYO' #Leancloud应用的appId
 verify: false #验证码
 notify: false #评论回复提醒
 avatar: '' #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 avatar_cdn: 'https://sdn.geekzu.org/avatar/' #头像CDN
 placeholder: '友情提醒，留下正确的邮箱地址可以第一时间获取评论反馈' #评论框占位符
 pageSize: 12 #评论分页
 visitor: true #阅读统计

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# MarkDown文件下载地址,如：http://md.xxwhite.com
mdhost: 'https://raw.githubusercontent.com/MonoLogueChi/www.xxwhite.com/master/source/_posts'

#pangu.js，中英文混排优化
pangu: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于本站'

friends:
  叉叉白: 'https://www.xxwhite.com/'
  大姐姐的博客Minemine: 'https://minemine.cc/'
  酷安基佬: 'http://socoolapk.top/'
  Se7en: 'https://www.se7ensec.cn/'
  姬长信: 'https://blog.isoyu.com/'
  staunchkai: 'http://staunchkai.com/'
  随遇而安: 'https://www.iszy.cc/'
  2401的晚秋咖啡: 'https://zsh2401.top/'
  Junzhou Liu: 'https://liujunzhou.top/'
  Yi-Yun: 'https://yi-yun.github.io/'  
  LmCjl在线工具: 'https://www.lmcjl.com'
  
aboutme: 叉叉白<br><br>一个小白搞机的记事本

